<?php
/**
 * Cartin24
 * @package    Cartin24_MultiWishlist
 * @copyright  Copyright (c) 2015-2016 Cartin24. (http://www.cartin24.com)
 * @license    http://opensource.org/licenses/osl-3.0.php   Open Software License (OSL 3.0)
 */
/* @var $this Mage_Wishlist_Block_Customer_Wishlist */
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="my-wishlist">
        <div class="page-title title-buttons">
            <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
                <a href="<?php echo $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>" class="link-rss"><?php echo $this->__('RSS Feed') ?></a>
            <?php endif; ?>
            <h1><?php echo $this->getTitle(); ?></h1>
        </div>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
	<div>
  <?php echo $this->getChildHtml('createwishlist');?>
	</div>

        <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" method="post">
            <?php echo $this->getChildHtml('top'); ?>
            <div class="fieldset">
                <?php if ($this->hasWishlistItems()): ?>
                        <?php echo $this->getBlockHtml('formkey');?>
                <?php endif; ?>
          <div>
		<div id="loadingmask" style="display: none;">
            <img id="loading" src="<?php echo $this->getSkinUrl('multiwishlist/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading...') ?>"/> 
		</div>
        <ul class="tabs" data-persist="true">
            <li><a href="#view1">Main</a></li>
             <?php 
             $model = Mage::getModel('multiwishlist/wishlistlabels');
             $labels = $model->getWishlistLabels();
             $i = 1; 
             foreach($labels as $label): 
             $i++;                
              ?>

            <li><a href="#view<?php echo $i;?>"><?php echo $label->getWishlistName()?></a></li>
            <?php endforeach;?>
        </ul>
       
      
        <div class="tabcontents">
                      
                        <?php $this->getChild('items')->setItems($this->getWishlistItems()); ?>
                         <div id="tabcontents">  <?php echo $this->getChildHtml('items');?>
                        <script type="text/javascript">decorateTable('wishlist-table')</script></div>
    </div>
          
                <div class="buttons-set buttons-set2">
                    <?php echo $this->getChildHtml('control_buttons');?>
                </div>
            </div></div>
        </form>

        <form id="wishlist-allcart-form" action="<?php echo $this->getUrl('*/*/allcart') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="wishlist_id" id="wishlist_id" value="<?php echo $this->getWishlistInstance()->getId() ?>" />
                <input type="hidden" name="qty" id="qty" value="" />
            </div>
        </form>

        <script type="text/javascript">
        //<![CDATA[
            var wishlistForm = new Validation($('wishlist-view-form'));
            var wishlistAllCartForm = new Validation($('wishlist-allcart-form'));

            function calculateQty() {
                var itemQtys = new Array();
                $$('#wishlist-view-form .qty').each(
                    function (input, index) {
                        var idxStr = input.name;
                        var idx = idxStr.replace( /[^\d.]/g, '' );
                        itemQtys[idx] = input.value;
                    }
                );

                $$('#qty')[0].value = JSON.stringify(itemQtys);
            }

            function addAllWItemsToCart() {
                calculateQty();
                wishlistAllCartForm.form.submit();
            }
        //]]>
        </script>
    </div>
    <?php echo $this->getChildHtml('bottom'); ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
<?php endif ?>
