<div class="block block-subscribe">
    <div class="block-title">
        <strong><span><?php echo $this->__('Newsletter') ?></span></strong>
    </div>
    <form action="/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
            </div>

            <?php echo $this->getChildHtml('newsletter.additional') ?>
            <br/>
            <select id="mce-MMERGE3" name="sign_type">
                <option value=""></option>
                <option value="Erhverv">Erhverv</option>
                <option value="Privat">Privat</option>
            </select>
            <br/>
            <select id="mce-MMERGE3" name="store_type">
                <option value=""></option>
                <option value="Aalborg">Aalborg</option>
                <option value="Aarhus">Aarhus</option>
                <option value="Horsens">Horsens</option>
                <option value="Vejle">Vejle</option>
                <option value="Randers">Randers</option>
                <option value="Odense">Odense</option>
                <option value="Roskilde">Roskilde</option>
                <option value="Anden/webshop">Other / shop</option>
            </select>

            <div class="input-box">
                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
        //]]>
    </script>
</div>