<div class="block block-subscribe">
    <div class="block-title">
        <strong><span><?php echo $this->__('Newsletter') ?></span></strong>
    </div>
    <form action="/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail" class="tvform_newsletter">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
            </div>

            <?php echo $this->getChildHtml('newsletter.additional') ?>
            <!--            <br/>
                        <select id="mce-MMERGE3" name="sign_type">
                            <option value=""></option>
                            <option value="Erhverv">Erhverv</option>
                            <option value="Privat">Privat</option>
                        </select>
                        <br/>
                        <select id="mce-MMERGE3" name="store_type">
                            <option value=""></option>
                            <option value="Aalborg">Aalborg</option>
                            <option value="Aarhus">Aarhus</option>
                            <option value="Horsens">Horsens</option>
                            <option value="Vejle">Vejle</option>
                            <option value="Randers">Randers</option>
                            <option value="Odense">Odense</option>
                            <option value="Roskilde">Roskilde</option>
                            <option value="Anden/webshop">Other / shop</option>
                        </select>-->

            <div class="input-box">
                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
                <div class="validation-advice" style="display: none;" id="advice-validate-email-newsletter">Please enter a valid email address. For example johndoe@domain.com.</div>
            </div>
            <div class="actions">
                <button id="newsletter_footer" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button fancyboxfake2"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
            <button style="display: none;" class="fancyboxfake2 button btn-inline"><span><span>Subscribe</span></span></button>
            <a class="fancybox2" href="#tvdivrecaptcha"></a>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        //var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
        //]]>
    </script>
</div>

<link href="<?php echo $this->getJsUrl('fancybox/jquery.fancybox.css') ?>" type="text/css" rel="stylesheet"/>
<script src="<?php echo $this->getJsUrl('fancybox/jquery.fancybox.js') ?>" type="text/javascript"></script>
<script type="text/javascript">
    var $site_key = '<?php echo Mage::getStoreConfig('mgroup_subrecaptcha/general/sitekey', Mage::app()->getStore()); ?>';
    var widgetId2;

    var onloadCallback = function () {
        // Renders the HTML element with id 'example1' as a reCAPTCHA widget.
        // The id of the reCAPTCHA widget is assigned to 'widgetId1'.
        widgetId2 = grecaptcha.render('tvrecaptcha2', {
            'sitekey': $site_key,
            'theme': 'light'
        });
    };
    jQuery(document).ready(function ($) {
        $('.fancybox2').fancybox({
            minWidth: 310,
            beforeLoad: function () {
                $('#tvrecaptcha2').html('');
            },
            beforeShow: function () {
                grecaptcha.reset(widgetId2);
            },
            afterClose: function () {
                strwidgetId2 = grecaptcha.getResponse(widgetId2);
                if (grecaptcha.getResponse(widgetId2) != '' || strwidgetId2) {
                    jQuery('#newsletter-validate-detail.tvform_newsletter').submit();
                }else{
                    $('#advice-validate-email-newsletter').html('Please confirm captcha to before proceed').show();
                }
            }
        });
        $('.fancyboxfake2').click(function (e) {
            e.preventDefault();
            var newsletter = $('.tvform_newsletter #newsletter').val();
            var arrEmail = newsletter.split('@yahoo.com');
            $('#advice-validate-email-newsletter').hide();
            if (!/^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(newsletter)) {
                $('#advice-validate-email-newsletter').html('Please enter a valid email address. For example johndoe@domain.com.').show();
                return false;
            }
            if (!/[a-z]/.test(arrEmail[0]) && arrEmail.length == 2) {
                $('#advice-validate-email-newsletter').html('Please enter a valid email address. For example johndoe@domain.com.').show();
                return false;
            }
            $('.fancybox2').click();
        })
    })
</script>
<div style="display: none">
    <div id="tvdivrecaptcha">
        <div id="tvrecaptcha_2">
            <div id="tvrecaptcha2"></div>	
            <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
                    async defer>
            </script>  
        </div>
    </div>
</div>