<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Js $this */ ?>
<script type="text/javascript" src="<?php echo $this->getJsUrl('creativestyle/amazonpayments.min.js'); ?>"></script>
<script type="text/javascript">
    AmazonPayments.setup(<?php echo $this->getJsConfig(); ?>);

    window.onAmazonPaymentsReady = function() {
        AmazonPayments
            .renderButtons()
<?php if ($this->getIsCheckout()) : ?>
<?php $orderReferenceId = $this->getOrderReferenceId(); ?>
<?php if ($orderReferenceId) : ?>
            .setOrderReferenceId('<?php echo $orderReferenceId; ?>')
<?php endif; ?>
            .initCheckout({
                responsive: true,
                urls: <?php echo $this->getCheckoutUrls(); ?>

            })
<?php endif; ?>
        ;
    };

<?php if ($this->isLoginActive()) : ?>
    window.onAmazonLoginReady = function() {
        AmazonPayments
            .initLogin()
<?php if ($this->getIsLogout()) : ?>
            .logout()
<?php endif; ?>
        ;
    };
<?php endif; ?>
</script>
<script async type="text/javascript" src="<?php echo $this->getWidgetJsUrl(); ?>"></script>
