<?php

/*
 * Created on : Mar 23, 2018, 9:44:18 PM
 * Author: Tran Trong Thang
 * Email: trantrongthang1207@gmail.com
 * Skype: trantrongthang1207
 */
?>
<?php

$isShowpage = Mage::getBlockSingleton('cms/page')->getPage()->getIsShowpage();
if ($isShowpage) {
    if (!Mage::getSingleton('customer/session')->isLoggedIn()) {
        $redirect_url = Mage::getUrl('customer/account/login');
		Mage::getSingleton('core/session')->addNotice('This page is only available to registered users.  Please login or register now.');
        Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->helper('core/url')->getCurrentUrl());
        Mage::app()->getFrontController()->getResponse()->setRedirect($redirect_url);
    } else {
        // logged in
    }
}
?>