<div class="block partfinder-horz-box">
        <div class="block-content">
			      <?php foreach($this->getLevelCollection() as $item): ?>
                <div class="level">
                  <?php echo $this->getLevelSelectHtml($item); ?>
                </div>
			      <?php endforeach; ?>

            <?php if ($this->getCategorySearchEnabled() == 1 || $this->getWordSearchEnabled() == 1): ?>      	
              <div id="partfinder_extra"  <?php if (!$this->productsFound()): ?> style="display:none" <?php endif; ?> >
              
                <?php if ($this->getCategorySearchEnabled() == 1): ?>            
                  <div id="partfinder_category_container">  
                    <?php foreach($this->getCategorySelects() as $selectHtml): ?>
                        <div class="level">
                          <?php echo $selectHtml; ?>
                        </div>
                    <?php endforeach; ?>                                    
                  </div>
                  <div style="clear:both;height:1px;"></div>
		            <?php endif; ?>	
		            	          


                <?php if ($this->getWordSearchEnabled() == 1): ?>
                  <div class="search" style="display: none">
                    <form action="#" onsubmit="partFinder.submitSearch(); return false;">
                       <table width="100%">
                         <tr>
                          <td class="pf-td-input">
                            <input id="partfinder_search" type="text" name="<?php echo $this->getSearchQueryParamName() ?>" value="<?php echo $this->getSearchQueryText() ?>" class="input-text"/>
                          </td>
                          <td class="pf-td-button">
                            <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
                          </td>
                         </tr>
                       </table>
                    </form>
		              </div>
		            <?php endif; ?>
		          </div>
		        <?php endif; ?>
		        <div id="partfinder_not_found" style="display:none"><?php echo $this->__('No matches found.') ?></div>			        		      	          		      	      
		    </div>
</div>
<script type="text/javascript">
//<![CDATA[	
  PartFinder.Config = {
    categorySelect  : ' <div class="level"><select class="partfinder-select" name="<?php echo $this->getCategoryParamName(); ?>" id="partfinder_category_select_{{select_id}}" onchange="partFinder.checkSubCategories({{select_id}}, this.value)">' +
                      '   <option value=""><?php echo $this->__('-- Select Category --') ?><\/option>' +
                      ' <\/select></div>',
                      
    url                    : '<?php echo $this->getRequestUrl(); ?>',
    submitUrl              : '<?php echo $this->getSubmitUrl(); ?>',    
    checkResultUrl         : '<?php echo $this->getCheckResultUrl(); ?>',   
    searchQueryParamName   : '<?php echo $this->getSearchQueryParamName(); ?>', 
    categoryParamName      : '<?php echo $this->getCategoryParamName(); ?>',          
    levelCount             : <?php echo $this->getLevelCount(); ?>,
    levelParameterNames    : <?php echo $this->getLevelParameterNames(); ?>,  
      
    categorySearchEnabled  : <?php echo $this->getCategorySearchEnabledStr(); ?>,
    wordSearchEnabled      : <?php echo $this->getWordSearchEnabledStr(); ?>,
    categorySelectCount    : <?php echo $this->getCategorySelectCount(); ?>    
  };

  var partFinder = new PartFinder.Main();
//]]>
</script>
